name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - type: prerelease
          - type: stable

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        submodules: true

    - name: Setup Environment Variables for headscale-webui submodule
      run: |
        cd headscale-webui/src
        echo "GIT_COMMIT_ARG=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "GIT_BRANCH_ARG=main" >> $GITHUB_ENV
        VERSION=$(git rev-parse HEAD || echo "unknown")
        echo "APP_VERSION_ARG=$VERSION" >> $GITHUB_ENV
        echo "BUILD_DATE_ARG=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
        cd -

    - name: Set HS_VERSION_ARG for Docker build
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        if [ "${{ matrix.type }}" == "prerelease" ]; then
          VERSION=$(curl -s https://api.github.com/repos/juanfont/headscale/releases | jq -r '[.[] | select(.prerelease == true)][0].tag_name')
        else
          VERSION=$(curl -s https://api.github.com/repos/juanfont/headscale/releases/latest | jq -r '.tag_name')
        fi
        echo "HS_VERSION_ARG=$VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          hotwa/headscale:${{ matrix.type == 'prerelease' && 'prerelease' || 'latest' }}
        build-args: |
          HEADSCALE_VERSION_TYPE= ${{ matrix.type }}
          GIT_COMMIT_ARG=${{ env.GIT_COMMIT_ARG }}
          GIT_BRANCH_ARG=${{ env.GIT_BRANCH_ARG }}
          APP_VERSION_ARG=${{ env.APP_VERSION_ARG }}
          BUILD_DATE_ARG=${{ env.BUILD_DATE_ARG }}
          HS_VERSION_ARG=${{ env.HS_VERSION_ARG }}
        platforms: linux/amd64,linux/arm64,linux/386

    - name: Print branch and tag information
      run: |
        echo "Branch: ${{ github.ref }}"
        echo "Computed tag: ${{ github.ref == 'refs/heads/prerelease' && 'prerelease' || 'latest' }}"

