name: Build and Push Multi-Arch Docker Image

on:
  # schedule:
  #   - cron: '0 0 * * *' # 每天运行一次
  push:
    branches:
      - main
      - prerelease

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            deb_arch: amd64
          - arch: arm64
            deb_arch: arm64
          - arch: 386
            deb_arch: 386

    steps:
    - name: Setup jq
      run: sudo apt-get update && sudo apt-get install -y jq
      
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        submodules: true

    - name: Determine Headscale .deb package URL
      run: |
        DEB_ARCH=${{ matrix.deb_arch }}
        if [ "${{ github.ref }}" == "refs/heads/prerelease" ]; then
          URL=$(curl -s https://api.github.com/repos/juanfont/headscale/releases \
          | jq -r --arg DEB_ARCH "$DEB_ARCH" '[.[] | select(.prerelease == true)][0].assets[] | select(.name | test("headscale_.*_" + $DEB_ARCH + "\\.deb")) | .browser_download_url')
        else
          URL=$(curl -s https://api.github.com/repos/juanfont/headscale/releases/latest \
          | jq -r --arg DEB_ARCH "$DEB_ARCH" '.assets[] | select(.name | test("headscale_.*_" + $DEB_ARCH + "\\.deb")) | .browser_download_url')
        fi
        echo "HEADSCALE_DEB_URL=$URL" >> $GITHUB_ENV


    - name: Download Headscale .deb package for the architecture
      run: wget "${{ env.HEADSCALE_DEB_URL }}" -O headscale.deb

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          hotwa/headscale:${{ github.ref == 'refs/heads/prerelease' && 'prerelease' || 'latest' }}
          hotwa/headscale:${{ github.sha }}
        build-args: HEADSCALE_DEB=headscale.deb
        platforms: linux/amd64,linux/arm64,linux/386

    - name: Print branch and tag information
      run: |
        echo "Branch: ${{ github.ref }}"
        echo "Computed tag: ${{ github.ref == 'refs/heads/prerelease' && 'prerelease' || 'latest' }}"

